version: '3.7'

services:
    postgres:
        image: postgres:13
        ports:
            - 9001:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=qq
            - POSTGRES_PASSWORD=qq
            - POSTGRES_DB=brain

volumes:
    postgres:
